# CMake generated Testfile for 
# Source directory: E:/projects/enc/navscene-sdk/tests
# Build directory: E:/projects/enc/navscene-sdk/build-gdal-verify/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-smoke]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-smoke.exe")
  set_tests_properties([=[navscene-smoke]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;17;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-smoke]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-smoke.exe")
  set_tests_properties([=[navscene-smoke]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;17;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-smoke]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-smoke.exe")
  set_tests_properties([=[navscene-smoke]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;17;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-smoke]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-smoke.exe")
  set_tests_properties([=[navscene-smoke]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;17;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-error-paths]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-error-paths.exe")
  set_tests_properties([=[navscene-error-paths]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;37;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-error-paths]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-error-paths.exe")
  set_tests_properties([=[navscene-error-paths]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;37;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-error-paths]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-error-paths.exe")
  set_tests_properties([=[navscene-error-paths]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;37;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-error-paths]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-error-paths.exe")
  set_tests_properties([=[navscene-error-paths]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;37;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-error-paths]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-portrayal-mvp]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-portrayal-mvp.exe")
  set_tests_properties([=[navscene-portrayal-mvp]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;56;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-portrayal-mvp]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-portrayal-mvp.exe")
  set_tests_properties([=[navscene-portrayal-mvp]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;56;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-portrayal-mvp]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-portrayal-mvp.exe")
  set_tests_properties([=[navscene-portrayal-mvp]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;56;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-portrayal-mvp]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-portrayal-mvp.exe")
  set_tests_properties([=[navscene-portrayal-mvp]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;56;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-portrayal-mvp]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-portrayal-catalog]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-portrayal-catalog.exe")
  set_tests_properties([=[navscene-portrayal-catalog]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;75;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-portrayal-catalog]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-portrayal-catalog.exe")
  set_tests_properties([=[navscene-portrayal-catalog]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;75;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-portrayal-catalog]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-portrayal-catalog.exe")
  set_tests_properties([=[navscene-portrayal-catalog]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;75;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-portrayal-catalog]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-portrayal-catalog.exe")
  set_tests_properties([=[navscene-portrayal-catalog]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;75;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-portrayal-catalog]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-chart-selection]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-chart-selection.exe")
  set_tests_properties([=[navscene-chart-selection]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;94;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-chart-selection]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-chart-selection.exe")
  set_tests_properties([=[navscene-chart-selection]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;94;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-chart-selection]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-chart-selection.exe")
  set_tests_properties([=[navscene-chart-selection]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;94;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-chart-selection]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-chart-selection.exe")
  set_tests_properties([=[navscene-chart-selection]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;94;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-chart-selection]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-chart-scene-builder-filters]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-chart-scene-builder-filters.exe")
  set_tests_properties([=[navscene-chart-scene-builder-filters]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;113;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-chart-scene-builder-filters]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-chart-scene-builder-filters.exe")
  set_tests_properties([=[navscene-chart-scene-builder-filters]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;113;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-chart-scene-builder-filters]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-chart-scene-builder-filters.exe")
  set_tests_properties([=[navscene-chart-scene-builder-filters]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;113;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-chart-scene-builder-filters]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-chart-scene-builder-filters.exe")
  set_tests_properties([=[navscene-chart-scene-builder-filters]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;113;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-chart-scene-builder-filters]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-scene-signature]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-scene-signature.exe")
  set_tests_properties([=[navscene-scene-signature]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;132;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-scene-signature]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-scene-signature.exe")
  set_tests_properties([=[navscene-scene-signature]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;132;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-scene-signature]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-scene-signature.exe")
  set_tests_properties([=[navscene-scene-signature]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;132;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-scene-signature]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-scene-signature.exe")
  set_tests_properties([=[navscene-scene-signature]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;132;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-scene-signature]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-scene-svg]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-scene-svg.exe")
  set_tests_properties([=[navscene-scene-svg]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;151;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-scene-svg]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-scene-svg.exe")
  set_tests_properties([=[navscene-scene-svg]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;151;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-scene-svg]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-scene-svg.exe")
  set_tests_properties([=[navscene-scene-svg]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;151;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-scene-svg]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-scene-svg.exe")
  set_tests_properties([=[navscene-scene-svg]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;151;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-scene-svg]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-projected-chart-scene]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-projected-chart-scene.exe")
  set_tests_properties([=[navscene-projected-chart-scene]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;170;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-projected-chart-scene]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-projected-chart-scene.exe")
  set_tests_properties([=[navscene-projected-chart-scene]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;170;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-projected-chart-scene]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-projected-chart-scene.exe")
  set_tests_properties([=[navscene-projected-chart-scene]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;170;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-projected-chart-scene]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-projected-chart-scene.exe")
  set_tests_properties([=[navscene-projected-chart-scene]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;170;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-projected-chart-scene]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-label-layout]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-label-layout.exe")
  set_tests_properties([=[navscene-label-layout]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;189;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-label-layout]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-label-layout.exe")
  set_tests_properties([=[navscene-label-layout]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;189;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-label-layout]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-label-layout.exe")
  set_tests_properties([=[navscene-label-layout]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;189;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-label-layout]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-label-layout.exe")
  set_tests_properties([=[navscene-label-layout]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;189;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-label-layout]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-polygon-triangulation]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-polygon-triangulation.exe")
  set_tests_properties([=[navscene-polygon-triangulation]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;208;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-polygon-triangulation]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-polygon-triangulation.exe")
  set_tests_properties([=[navscene-polygon-triangulation]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;208;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-polygon-triangulation]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-polygon-triangulation.exe")
  set_tests_properties([=[navscene-polygon-triangulation]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;208;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-polygon-triangulation]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-polygon-triangulation.exe")
  set_tests_properties([=[navscene-polygon-triangulation]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;208;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-polygon-triangulation]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-layer-composition]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-layer-composition.exe")
  set_tests_properties([=[navscene-layer-composition]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;227;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-layer-composition]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-layer-composition.exe")
  set_tests_properties([=[navscene-layer-composition]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;227;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-layer-composition]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-layer-composition.exe")
  set_tests_properties([=[navscene-layer-composition]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;227;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-layer-composition]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-layer-composition.exe")
  set_tests_properties([=[navscene-layer-composition]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;227;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-layer-composition]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-vulkan-win32-render-modes]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-vulkan-win32-render-modes.exe")
  set_tests_properties([=[navscene-vulkan-win32-render-modes]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;251;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-vulkan-win32-render-modes]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-vulkan-win32-render-modes.exe")
  set_tests_properties([=[navscene-vulkan-win32-render-modes]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;251;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-vulkan-win32-render-modes]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-vulkan-win32-render-modes.exe")
  set_tests_properties([=[navscene-vulkan-win32-render-modes]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;251;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-vulkan-win32-render-modes]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-vulkan-win32-render-modes.exe")
  set_tests_properties([=[navscene-vulkan-win32-render-modes]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;251;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-vulkan-win32-render-modes]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-s57-samples]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-s57-samples.exe")
  set_tests_properties([=[navscene-s57-samples]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;295;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-s57-samples]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-s57-samples.exe")
  set_tests_properties([=[navscene-s57-samples]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;295;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-s57-samples]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-s57-samples.exe")
  set_tests_properties([=[navscene-s57-samples]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;295;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-s57-samples]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-s57-samples.exe")
  set_tests_properties([=[navscene-s57-samples]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;295;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-s57-samples]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-s57-reference-render]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Debug/navscene-s57-reference-render.exe")
  set_tests_properties([=[navscene-s57-reference-render]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;319;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-s57-reference-render]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/Release/navscene-s57-reference-render.exe")
  set_tests_properties([=[navscene-s57-reference-render]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;319;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-s57-reference-render]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/MinSizeRel/navscene-s57-reference-render.exe")
  set_tests_properties([=[navscene-s57-reference-render]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;319;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-s57-reference-render]=] "E:/projects/enc/navscene-sdk/build-gdal-verify/tests/RelWithDebInfo/navscene-s57-reference-render.exe")
  set_tests_properties([=[navscene-s57-reference-render]=] PROPERTIES  ENVIRONMENT "GDAL_DATA=E:/OSGeo4W/apps/gdal/share/gdal;PROJ_LIB=E:/OSGeo4W/share/proj;NAVSCENE_S57_SAMPLE_ROOT=E:/projects/enc/navscene-sdk/../enc" ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:E:/OSGeo4W/bin;PATH=path_list_prepend:C:/VulkanSDK/1.4.341.1/Bin" _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;319;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-s57-reference-render]=] NOT_AVAILABLE)
endif()
