# CMake generated Testfile for 
# Source directory: E:/projects/enc/navscene-sdk/tests
# Build directory: E:/projects/enc/navscene-sdk/build-vk-probe/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-smoke]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/Debug/navscene-smoke.exe")
  set_tests_properties([=[navscene-smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;16;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-smoke]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/Release/navscene-smoke.exe")
  set_tests_properties([=[navscene-smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;16;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-smoke]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/MinSizeRel/navscene-smoke.exe")
  set_tests_properties([=[navscene-smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;16;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-smoke]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/RelWithDebInfo/navscene-smoke.exe")
  set_tests_properties([=[navscene-smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;16;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-error-paths]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/Debug/navscene-error-paths.exe")
  set_tests_properties([=[navscene-error-paths]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;32;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-error-paths]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/Release/navscene-error-paths.exe")
  set_tests_properties([=[navscene-error-paths]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;32;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-error-paths]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/MinSizeRel/navscene-error-paths.exe")
  set_tests_properties([=[navscene-error-paths]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;32;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-error-paths]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/RelWithDebInfo/navscene-error-paths.exe")
  set_tests_properties([=[navscene-error-paths]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;32;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-error-paths]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-portrayal-mvp]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/Debug/navscene-portrayal-mvp.exe")
  set_tests_properties([=[navscene-portrayal-mvp]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;51;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-portrayal-mvp]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/Release/navscene-portrayal-mvp.exe")
  set_tests_properties([=[navscene-portrayal-mvp]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;51;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-portrayal-mvp]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/MinSizeRel/navscene-portrayal-mvp.exe")
  set_tests_properties([=[navscene-portrayal-mvp]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;51;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-portrayal-mvp]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/RelWithDebInfo/navscene-portrayal-mvp.exe")
  set_tests_properties([=[navscene-portrayal-mvp]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;51;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-portrayal-mvp]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-scene-signature]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/Debug/navscene-scene-signature.exe")
  set_tests_properties([=[navscene-scene-signature]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;70;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-scene-signature]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/Release/navscene-scene-signature.exe")
  set_tests_properties([=[navscene-scene-signature]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;70;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-scene-signature]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/MinSizeRel/navscene-scene-signature.exe")
  set_tests_properties([=[navscene-scene-signature]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;70;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-scene-signature]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/RelWithDebInfo/navscene-scene-signature.exe")
  set_tests_properties([=[navscene-scene-signature]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;70;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-scene-signature]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-scene-svg]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/Debug/navscene-scene-svg.exe")
  set_tests_properties([=[navscene-scene-svg]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;89;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-scene-svg]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/Release/navscene-scene-svg.exe")
  set_tests_properties([=[navscene-scene-svg]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;89;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-scene-svg]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/MinSizeRel/navscene-scene-svg.exe")
  set_tests_properties([=[navscene-scene-svg]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;89;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-scene-svg]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/RelWithDebInfo/navscene-scene-svg.exe")
  set_tests_properties([=[navscene-scene-svg]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;89;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-scene-svg]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[navscene-s57-samples]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/Debug/navscene-s57-samples.exe")
  set_tests_properties([=[navscene-s57-samples]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;114;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[navscene-s57-samples]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/Release/navscene-s57-samples.exe")
  set_tests_properties([=[navscene-s57-samples]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;114;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[navscene-s57-samples]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/MinSizeRel/navscene-s57-samples.exe")
  set_tests_properties([=[navscene-s57-samples]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;114;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[navscene-s57-samples]=] "E:/projects/enc/navscene-sdk/build-vk-probe/tests/RelWithDebInfo/navscene-s57-samples.exe")
  set_tests_properties([=[navscene-s57-samples]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;114;add_test;E:/projects/enc/navscene-sdk/tests/CMakeLists.txt;0;")
else()
  add_test([=[navscene-s57-samples]=] NOT_AVAILABLE)
endif()
